# This workflow contains the most common jobs that are used in the CI of the k6's extensions.
# We created it to maintain the same standards that has the k6's core.
name: Extension Check

# Define when this workflow should be triggered.
on:
  # Run on all pull requests.
  pull_request:
  # Run on all pushes to any branch.
  push:
  # Allow this workflow to be called from other workflows as a reusable workflow.
  workflow_call:
  # Enable manually triggering this workflow via the API or web UI.
  workflow_dispatch:

# Set default configuration for all run commands in this workflow.
defaults:
  run:
    # Use bash as the default shell for all run steps.
    shell: bash

# Define all jobs that will run as part of this workflow.
jobs:
  # Job to check code quality and style using golangci-lint.
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code with full git history.
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          # Fetch all commits and branches for complete history.
          fetch-depth: 0
      # Run golangci-lint to check code quality, style, and potential bugs.
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0

  # Job to test the extension on multiple Go versions and platforms.
  test-go-versions:
    runs-on: ${{ matrix.platform }}
    strategy:
      # Continue running other matrix jobs even if one fails.
      fail-fast: false
      # Create a matrix of 4 jobs: 2 Go versions × 2 platforms.
      matrix:
        go-version: [1.24.x, 1.25.x]
        platform: [ubuntu-latest, windows-latest]
    steps:
      # Checkout the repository code.
      - name: Checkout code
        uses: actions/checkout@v5
      # Install the Go version specified in the matrix.
      - name: Install Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          # Use the Go version from the matrix.
          go-version: ${{ matrix.go-version }}
      # Run all tests with race detection.
      - name: Run tests
        run: |
          # Show which Go binary is being used.
          which go
          # Display the Go version.
          go version
          # Run tests with race detector, 800 second timeout, for all packages.
          go test -race -timeout 800s ./...

  # Job to verify that the extension builds correctly with xk6.
  test-build:
    runs-on: ${{ matrix.platform }}
    strategy:
      # Continue running other matrix jobs even if one fails.
      fail-fast: false
      # Create a matrix of 2 jobs: 2 platforms.
      matrix:
        platform: [ubuntu-latest, windows-latest]
    steps:
      # Checkout the repository code.
      - name: Checkout code
        uses: actions/checkout@v5
      # Install Go 1.25.x for the build test.
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          # Use Go version 1.25.x.
          go-version: 1.25.x
      # Build the k6 binary with this extension and verify it works.
      - name: Check build
        run: |
          # Display the Go version being used.
          go version
          # Show current directory and list its contents.
          pwd && ls -l

          # Install the xk6 builder tool from the master branch.
          go install go.k6.io/xk6/cmd/xk6@master
          # Get the current module name (e.g., github.com/oshokin/xk6-kv).
          MODULE_NAME=`go list -m`

          # Build the k6 binary with this extension and verify it works.
          GOPRIVATE="go.k6.io/k6" xk6 build \
            --output ./k6ext \
            --with $MODULE_NAME="."
          ./k6ext version